[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
campaign_registry = "Camp1111111111111111111111111111111111111111"
task_manager = "Task1111111111111111111111111111111111111111"
budget_vote = "Budg1111111111111111111111111111111111111111"
task_escrow = "Escr1111111111111111111111111111111111111111"
proof_registry = "Prof1111111111111111111111111111111111111111"
dispute_module = "Disp1111111111111111111111111111111111111111"
governance_token = "Gove1111111111111111111111111111111111111111"

[programs.devnet]
campaign_registry = "Camp1111111111111111111111111111111111111111"
task_manager = "Task1111111111111111111111111111111111111111"
budget_vote = "Budg1111111111111111111111111111111111111111"
task_escrow = "Escr1111111111111111111111111111111111111111"
proof_registry = "Prof1111111111111111111111111111111111111111"
dispute_module = "Disp1111111111111111111111111111111111111111"
governance_token = "Gove1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"
